services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    restart: unless-stopped
    network_mode: host
    environment:
      NODE_EXTRA_CA_CERTS: /app/data/ca.crt
    labels:
      traefik.enable: true
      traefik.http.services.uptime-kuma.loadbalancer.server.port: 3001
      traefik.http.routers.uptime-kuma.rule: Host(`monitoring`)
      traefik.http.routers.uptime-kuma.middlewares: uptime-kuma-ipallowlist
      traefik.http.middlewares.uptime-kuma-ipallowlist.ipallowlist.sourcerange: >
        2a00:23c8:bda0:b310::/64,
        10.10.0.0/16
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /containers/uptime-kuma:/app/data
