services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    restart: unless-stopped
    networks:
      - monitoring
      - proxy
    environment:
      NODE_EXTRA_CA_CERTS: /app/data/ca.crt
    labels:
      traefik.enable: true
      traefik.http.routers.uptime-kuma.rule: Host(`monitoring`)
      traefik.http.routers.uptime-kuma.middlewares: trusted-ipallowlist, authentik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /containers/uptime-kuma:/app/data

networks:
  monitoring:
    enable_ipv6: true
    name: monitoring
  proxy:
    external: true
